### ISSUE TITLE
Pod can't access itself with ClusterIP when using Calico

### ISSUE THREAD

**Issue by pavels** [sbezverk/nfproxy#53]
Pod can't access itsel using ClusterIP when using calico

This is actually this bug - https://github.com/kubernetes/kubernetes/issues/19983

Calico uses mark as well, messing with nfproxy - actually nfproxy should never set or test whole mark but rather use bitwise & and masks.

I would volunteer to make PR, problem is, https://github.com/sbezverk/nftableslib can't do such operation - as mask operation on mark is probably common, maybe it could be done in a way, that another field is added to `MetaMark` called `Mask` (or something like that) and if set, that would be used for set and compare operations. Would you accept such PR?

**Comment by sbezverk** [comment]
@pavels  PRs are always welcome, FYI I am in the process of updating `nfproxy` to support k8s v1.20.1. There was a change in service's dual stack support.  Meanwhile you can propose a solution in ` https://github.com/sbezverk/nftableslib` to support Mask.

**Comment by pavels** [comment]
Hi

the proposed change is here https://github.com/sbezverk/nftableslib/pull/91

I also already did needed changes in nfproxy and tested in cluster - it solves the problem

The changes in nfproxy are very small.
